# Generated by Django 5.0.3 on 2024-04-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Retsept nomi')),
                ('content', models.TextField(verbose_name='Retsept')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('views', models.IntegerField(default=0, verbose_name='Korishlar soni')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
                'ordering': ['pk'],
            },
        ),
    ]
