# Generated by Django 5.0.3 on 2024-04-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='updated',
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Saytga chiqarish'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Retsept'),
        ),
    ]
