# Generated by Django 5.0.3 on 2024-04-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_recipe_updated_recipe_photo_recipe_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='views',
        ),
    ]
